import { UPDATE_RENTANDLEASE_NEW_APPLICATION_FORMType, SET_RENTANDLEASE_NEW_APPLICATION_STEPType, RESET_RENTANDLEASE_NEW_APPLICATION_FORMType } from "./types";

export const UPDATE_RENTANDLEASE_NEW_APPLICATION_FORM = (key, value) => ({
  type: UPDATE_RENTANDLEASE_NEW_APPLICATION_FORMType,
  payload: { key, value },
});

export const SET_RENTANDLEASE_NEW_APPLICATION_STEP = (step) => ({
  type: SET_RENTANDLEASE_NEW_APPLICATION_STEPType,
  payload: step,
});

export const RESET_RENTANDLEASE_NEW_APPLICATION_FORM = () => ({
  type: RESET_RENTANDLEASE_NEW_APPLICATION_FORMType,
});

