export const UPDATE_GC_NEW_APPLICATION_FORM = "UPDATE_GC_NEW_APPLICATION_FORM";
export const SET_GC_NEW_APPLICATION_FORM_STEP = "SET_GC_NEW_APPLICATION_FORM_STEP";
export const RESET_STATE = "RESET_STATE";
