const { createProxyMiddleware } = require("http-proxy-middleware");
const BATHINDA_API_URL = "https://apipmidc.mcbathinda.com";

const createProxy = createProxyMiddleware({
  //target: process.env.REACT_APP_PROXY_API || "https://uat.digit.org",
  // target: process.env.REACT_APP_PROXY_API || "https://qa.digit.org",
  target: process.env.REACT_APP_PROXY_API || "https://upyog-test.niua.org",
  // target: process.env.REACT_APP_PROXY_API || "https://mseva-uat.lgpunjab.gov.in/",
  changeOrigin: true,
});
const assetsProxy = createProxyMiddleware({
  target: process.env.REACT_APP_PROXY_ASSETS || "https://upyog-test.niua.org",
  // target: process.env.REACT_APP_PROXY_ASSETS || "https://mseva-uat.lgpunjab.gov.in/",
  changeOrigin: true,
});

const bathindaProxy = createProxyMiddleware({
  target: BATHINDA_API_URL,
  changeOrigin: true,
})

module.exports = function (app) {
  [
    "/access/v1/actions/mdms",
    "/egov-mdms-service",
    "/egov-location",
    "/localization",
    "/egov-workflow-v2",
    "/pgr-services",
    "/swach-services",
    "/filestore",
    "/egov-hrms",
    "/user-otp",
    "/user",
    "/fsm",
    "/billing-service",
    "/collection-services",
    "/pdf-service",
    "/pg-service",
    "/vehicle",
    "/vendor",
    //added this new rainmaker-pgr
    "/rainmaker-pgr",
    "/property-services",
    "/fsm-calculator/v1/billingSlab/_search",
    "/pt-calculator-v2",
    "/dashboard-analytics",
    "/echallan-services",
    "/egov-searcher/bill-genie/mcollectbills/_get",
    "/egov-searcher/bill-genie/billswithaddranduser/_get",
    "/egov-searcher/bill-genie/waterbills/_get",
    "/egov-searcher/bill-genie/seweragebills/_get",
    "/egov-pdf/download/UC/mcollect-challan",
    "/egov-hrms/employees/_count",
    "/tl-services/v1/_create",
    "/tl-services/v1/_search",
    "/egov-url-shortening/shortener",
    "/inbox/v1/_search",
    "/tl-services",
    "/tl-calculator",
    "/edcr",
    "/bpa-services",
    "/noc-services",
    "/egov-user-event",
    "/egov-document-uploader",
    "/egov-pdf",
    "/egov-survey-services",
    "/ws-services",
    "/sw-services",
    "/ws-calculator",
    "/sw-calculator/",
    "/egov-searcher",
    "/report",
    "/inbox/v1/dss/_search",
    "/inbox/v1/elastic/_search",
    "/fsm-calculator",
    "/service-request",
    "/pet-services/pet-registration/_create",
    "/pet-services/pet-registration/_search",
    "/pet-services/pet-registration/_update",
    "/billing-service/bill/v2/_fetchbill",
    "/collection-services/payments/pet-services/_search",
    "/requester-services-dx",
    "/sv-services/street-vending/_create",
    "/sv-services/street-vending/_search",
    "/sv-services/street-vending/_update",
    "/sv-services/street-vending/_deletedraft",
    "/chb-services/booking/v1/_create",
    "/chb-services/booking/v1/_search",
    "/chb-services/booking/v1/_update",
    "/chb-services/booking/v1/_slot-search",
    "/chb-services/booking/v1/_estimate",
    "/asset-services/v1/assets/_create",
    "/asset-services/v1/assets/_search",
    "/asset-services/v1/assets/_update",
    "/asset-services/v1/assets/assignment/_create",
    "/asset-services/v1/assets/assignment/_update",
    "/asset-services/v1/assets/_search",
    "/asset-services/v1/assets/depreciation/_process",
    "/asset-services/v1/assets/depreciation/list",
    "/asset-services/v1/disposal/_create",
    "/asset-services/maintenance/v1/_create",
    "/asset-services/maintenance/v1/_update",
    "/asset-services/maintenance/v1/_search",
    "/asset-services/v1/disposal/_search",
    "/asset-services/v1/assets/assignment/_search",
    "/pgr-ai-services/v1/request/_create",
    "/pgr-ai-services/v1/request/_search",
    "/pgr-ai-services/v1/request/_update",
    "/egov-esign",
    "/ndc-services",
    "/ndc-calculator",
    "/bpa-calculator",
    "/noc-calculator",
    "/challan-generation",
    "/layout-services",
    "/adv-services",
    "/rl-services",
    "/clu-services",
    "/clu-calculator",
    "/layout-calculator",
    "/gc-services",
  ].forEach((location) => app.use(location, createProxy));
  ["/pb-egov-assets"].forEach((location) => app.use(location, assetsProxy));
   ["/api/Property/", "/api/Property/GetPropertyDetail", "/api/Authenticate", "/api/Authenticate/GetToken"].forEach((location) =>
    app.use(location, bathindaProxy)
  );
};
