net.sf.jasperreports.subreport.runner.factory=net.sf.jasperreports.engine.fill.JRContinuationSubreportRunnerFactory
net.sf.jasperreports.export.xls.detect.cell.type=true
net.sf.jasperreports.compiler.class=net.sf.jasperreports.engine.design.JRJdtCompiler
