server
{
  listen 80;
  underscores_in_headers on;

  location /digit-ui
  {
    root /var/web;
    index index.html index.htm;
    try_files $uri $uri/ /digit-ui/index.html;
  }
  location /upyog-ui
  {
    root /var/web;
    index index.html index.htm;
    try_files $uri $uri/ /digit-ui/index.html;
  }

  location ~ ^/(access|egov-mdms-service|egov-location|localization|egov-workflow-v2|pgr-services|swach-services|filestore|egov-hrms|user-otp|user|fsm|billing-service|collection-services|pdf-service|pg-service|vehicle|vendor|rainmaker-pgr|property-services|fsm-calculator|pt-calculator-v2|dashboard-analytics|echallan-services|egov-searcher|egov-pdf|tl-services|tl-calculator|edcr|bpa-services|noc-services|egov-user-event|egov-document-uploader|egov-survey-services|ws-services|sw-services|ws-calculator|sw-calculator|report|inbox|service-request|pet-services|requester-services-dx|sv-services|chb-services|asset-services|pgr-ai-services|egov-esign|ndc-services|ndc-calculator|bpa-calculator|noc-calculator|challan-generation|layout-services|adv-services|rl-services|clu-services|clu-calculator|layout-calculator|gc-services|gc-calculator)
  {
    proxy_pass https://sdc-uat.lgpunjab.gov.in;
    proxy_ssl_server_name on;
    proxy_set_header Host sdc-uat.lgpunjab.gov.in;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
