export const UPDATE_EMPLOYEE_FORM = "UPDATE_EMPLOYEE_FORM";
export const SET_EMPLOYEE_STEP = "SET_EMPLOYEE_STEP";
export const SET_EMPLOYEE_VALIDITY = "SET_EMPLOYEE_VALIDITY";
export const RESET_EMPLOYEE_FORM = "RESET_EMPLOYEE_FORM";