// Session Storage Keys
export const SWACH_CITIZEN_CREATE_COMPLAINT = "SWACH_CITIZEN_CREATE_COMPLAINT";
export const SWACH_CITIZEN_COMPLAINT_CONFIG = "SWACH_CITIZEN_COMPLAINT_CONFIG";
export const PGR_CITIZEN_COMPLAINT_CONFIG = "PGR_CITIZEN_COMPLAINT_CONFIG";
export const PGR_CITIZEN_CREATE_COMPLAINT = "PGR_CITIZEN_CREATE_COMPLAINT";
