export const UPDATE_WS_NEW_APPLICATION_FORM = "UPDATE_WS_NEW_APPLICATION_FORM";
export const SET_WS_NEW_APPLICATION_FORM_STEP = "SET_WS_NEW_APPLICATION_FORM_STEP";
export const RESET_STATE="RESET_STATE";
