export const stepFormEditConfigCitizen = [
  {
      head: "ES_EDIT_APPLICATION_LOCATION_DETAILS",
      stepNumber: 1,
      body: [
        {
          route: "map",
          component: "PTSelectGeolocation",
          nextStep: "pincode",
          hideInEmployee: true,
          key: "address",
          texts: {
            header: "PT_GEOLOCATON_HEADER",
            cardText: "PT_GEOLOCATION_TEXT",
            nextText: "PT_COMMON_NEXT",
            skipAndContinueText: "CORE_COMMON_SKIP_CONTINUE",
          },
        },
        {
          route: "pincode",
          component: "PTSelectPincode",
          texts: {
            headerCaption: "PT_PROPERTY_LOCATION_CAPTION",
            header: "PT_PINCODE_LABEL",
            cardText: "PT_PINCODE_TEXT",
            submitBarLabel: "PT_COMMON_NEXT",
            skipText: "CORE_COMMON_SKIP_CONTINUE",
          },
          withoutLabel: true,
          key: "address",
          nextStep: "address",
          type: "component",
        },
        {
          route: "address",
          component: "PTSelectAddress",
          withoutLabel: true,
          texts: {
            headerCaption: "PT_PROPERTY_LOCATION_CAPTION",
            header: "CS_FILE_APPLICATION_PROPERTY_LOCATION_ADDRESS_TEXT",
            cardText: "CS_FILE_APPLICATION_PROPERTY_LOCATION_CITY_MOHALLA_TEXT",
            submitBarLabel: "PT_COMMON_NEXT",
          },
  
          key: "address",
          nextStep: "street",
          isMandatory: true,
          type: "component",
        },
        {
          type: "component",
          route: "street",
          component: "PTSelectStreet",
          key: "address",
          withoutLabel: true,
          texts: {
            headerCaption: "PT_PROPERTY_LOCATION_CAPTION",
            header: "CS_FILE_APPLICATION_PROPERTY_LOCATION_ADDRESS_TEXT",
            cardText: "PT_STREET_TEXT",
            submitBarLabel: "PT_COMMON_NEXT",
          },
          nextStep: "landmark",
        },
        {
          type: "component",
          isMandatory: true,
          component: "SurveyId",
          key: "surveyId",
          withoutLabel: true,
        },
        {
          type: "component",
          isMandatory: true,
          component: "YearOfCreation",
          key: "yearOfCreation",
          withoutLabel: true,
        },
      ],
    },
  {
      head: "ES_EDIT_APPLICATION_PROPERTY_ASSESSMENT",
      stepNumber: 2,
      body: [
        {
          type: "component",
          route: "property-usage-type",
          isMandatory: true,
          component: "PropertyUsageType",
          texts: {
            headerCaption: "PT_ASSESMENT_INFO_USAGE_TYPE",
            header: "PT_PROPERTY_DETAILS_USAGE_TYPE_HEADER",
            cardText: "PT_PROPERTY_DETAILS_USAGE_TYPE_TEXT",
            submitBarLabel: "PT_COMMONS_NEXT",
          },
          nextStep: "property-type",
          key: "usageCategoryMajor",
          withoutLabel: true,
        },
        {
          type: "component",
          isMandatory: true,
          component: "ProvideSubUsageType",
          key: "usageCategoryMinor",
          withoutLabel: true,
        },
        {
          type: "component",
          route: "property-type",
          isMandatory: true,
          component: "PropertyType",
          texts: {
            headerCaption: "",
            header: "PT_ASSESMENT1_PROPERTY_TYPE",
            cardText: "",
            submitBarLabel: "PT_COMMONS_NEXT",
          },
          nextStep: {
            COMMON_PROPTYPE_BUILTUP_INDEPENDENTPROPERTY: "number-of-floors",
            COMMON_PROPTYPE_BUILTUP_SHAREDPROPERTY: "provide-floor-no",
            COMMON_PROPTYPE_VACANT: "area",
          },
          key: "PropertyType",
          withoutLabel: true,
        },
        {
          type: "component",
          isMandatory: true,
          component: "Area",
          key: "landarea",
          withoutLabel: true,
        },
        {
          type: "component",
          isMandatory: true,
          component: "ProvideFloorNo",
          key: "noOfFloors",
          withoutLabel: true,
        },
        {
          type: "component",
          isMandatory: true,
          component: "BusinessName",
          key: "businessName",
          withoutLabel: true,
        },
        {
          type: "component",
          //"isMandatory": true,
          component: "Remarks",
          key: "remarks",
          withoutLabel: true,
        },
        // {
        //   type: "component",
        //   route: "number-of-floors",
        //   isMandatory: true,
        //   component: "PropertyFloorDetails",
        //   texts: {
        //     headerCaption: "",
        //     header: "BPA_SCRUTINY_DETAILS_NUMBER_OF_FLOORS_LABEL",
        //     cardText: "PT_PROPERTY_DETAILS_NO_OF_FLOORS_TEXT",
        //     submitBarLabel: "PT_COMMONS_NEXT",
        //   },
        //   nextStep: "number-of-basements@0",
        //   key: "noOfFloors",
        //   withoutLabel: true,
        // },
        {
          type: "component",
          component: "Units",
          key: "units",
          withoutLabel: true,
        },
        
      ],
    },
    {
      head: "ES_EDIT_APPLICATION_OWNERSHIP_DETAILS",
      stepNumber: 3,
      body: [
        {
          type: "component",
          route: "owner-ship-details@0",
          isMandatory: true,
          component: "SelectOwnerShipDetails",
          texts: {
            headerCaption: "PT_PROPERTIES_OWNERSHIP",
            header: "PT_PROVIDE_OWNERSHIP_DETAILS",
            cardText: "PT_PROVIDE_OWNERSHI_DETAILS_SUB_TEXT",
            submitBarLabel: "PT_COMMON_NEXT",
          },
          key: "ownershipCategory",
          withoutLabel: true,
          nextStep: {
            INSTITUTIONALPRIVATE: "inistitution-details",
            INSTITUTIONALGOVERNMENT: "inistitution-details",
            "INDIVIDUAL.SINGLEOWNER": "owner-details",
            "INDIVIDUAL.MULTIPLEOWNERS": "owner-details",
          },
        },
        
        {
          type: "component",
          component: "PTEmployeeOwnershipDetails",
          key: "owners",
          withoutLabel: true,
          hideInCitizen: true,
        },
      ],
    },
    {
      head: "ES_EDIT_APPLICATION_DOCUMENTS_REQUIRED",
      stepNumber: 4,
      body: [
        {
          component: "SelectDocuments",
          withoutLabel: true,
          key: "documents",
          type: "component",
        },
      ],
    },
    {
      head: "Summary",
      stepNumber: 5,
      body: [
        {
          component: "PTSummaryEdit",
          withoutLabel: true,
          key: "PTSummary",
          type: "component",
        },
      ],
    },
];
