logging.level.org.egov.search.repository=DEBUG

#--------------------------- DB CONFIGURATIONS ---------------------------#


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.44.237.25:5432/egov_prod_db_new
spring.datasource.username=egovprod
spring.datasource.password=jr88WZdM#4YU##1Q



#--------------------------- PATH & PORT CONFIGURATIONS ---------------------------#

# SET CONTEXT PATH
server.contextPath=/egov-searcher
server.servlet.context-path=/egov-searcher
server.port=8093

#----------------------------- FLYWAY CONFIGURATIONS ------------------------------#

spring.flyway.user=egovprod
spring.flyway.password=jr88WZdM#4YU##1Q
spring.flyway.outOfOrder=true
spring.flyway.table=pgr_rspring.spring.flyway.ema
spring.flyway.baseline-on-migrate=true
spring.flyway.url=jdbc:postgresql://10.44.237.25:5432/egov_prod_db_new
spring.flyway.locations=db/migration/ddl
spring.flyway.enabled=false

pagination.default.page.size=4000
pagination.default.offset=0

-# user path 
-egov.user.contextpath=http://egov-user:8080
-egov.user.searchpath=/user/_search

#----------------MDMS config---------------------#
egov.mdms.host=http://localhost:8094
egov.mdms.search.endpoint=egov-mdms-service/v1/_search

logging.pattern.console=%clr(%X{CORRELATION_ID:-}) %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

search.yaml.path=file:///C:/AmanKPMGwork/punjab-rainmaker-customization/configs/egov-searcher/bpa-labour-department-search.yml
operaters.list=GE,LE,NE,LIKE,ILIKE,TOUPPERCASE,TOLOWERCASE,=

spring.main.allow-bean-definition-overriding=true
spring.resources.cache.period=31536000ms

#------------egov-enc-service config----------------#
egov.enc.host=http://localhost:1234
egov.enc.encrypt.endpoint=/egov-enc-service/crypto/v1/_encrypt
egov.enc.decrypt.endpoint=/egov-enc-service/crypto/v1/_decrypt

egov.state.level.tenant.id=pb
state.level.tenant.id=pb

#-----------Kafka Audit Topic Name------------#
kafka.topic.audit=audit_data

#------------Kafka Config----------------------#
kafka.config.bootstrap_server_config=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

