export const UPDATE_SURVEY_FORM = "UPDATE_SURVEY_FORM";
export const SET_SURVEY_STEP = "SET_SURVEY_STEP";

// export const ADD_SECTION = 'ADD_SECTION';
// export const ADD_CATEGORY = 'ADD_CATEGORY';
// export const ADD_QUESTION = 'ADD_QUESTION';
// export const UPDATE_SECTION = 'UPDATE_SECTION';
// export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
// export const UPDATE_QUESTION = 'UPDATE_QUESTION';

export const FIELD_CHANGE = "FIELD_CHANGE";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_QUESTIONS = "ADD_QUESTIONS";
export const ADD_QUESTIONS_LIST = "ADD_QUESTIONS_LIST";
export const RECALCULATE_WEIGHTAGE = "RECALCULATE_WEIGHTAGE";
export const UPDATE_WEIGHTAGE = "UPDATE_WEIGHTAGE";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_QUESTION_SELECTION = "UPDATE_QUESTION_SELECTION";
export const UPDATE_MANDATORY_QUESTION_SELECTION = "UPDATE_MANDATORY_QUESTION_SELECTION";
export const UPDATE_QUESTION_WEIGHTAGE = "UPDATE_QUESTION_WEIGHTAGE";
export const SET_QUESTIONS = "SET_QUESTIONS";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const GO_PREV = "GO_PREV";
export const GO_NEXT = "GO_NEXT";

export const NEXT_STEP = "NEXT_STEP";
export const PREVIOUS_STEP = "PREVIOUS_STEP";
export const SET_STEP_DATA = "SET_STEP_DATA";
export const AUTO_CALCULATE_CATEGORY = "AUTO_CALCULATE_CATEGORY";
export const RESET_FORM = "RESET_FORM";
