module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  purge: { enabled: true, content: ["./example/index.html"] },
  theme: {
    screens: {
      dt: "780px",
    },
    colors: {
      primary: {
        light: "#1A5CA8",
        main: "#003C71",
        dark: "#002554",
      },
      secondary: "#B5451B",
      text: {
        primary: "#1F1F1F",
        secondary: "#505A5F",
      },
      link: {
        normal: "#003C71",
        hover: "#002554",
      },
      border: "#B1B4B6",
      "input-border": "#0B0C0C",
      focus: "#FFBF00",
      error: "#D4351C",
      success: "#00703C",
      black: "#000000",
      grey: {
        dark: "#626A6E",
        mid: "#DEE0E2",
        light: "#F8F8F8",
        bg: "#F3F2F1",
      },
      white: "#FFFFFF",
    },
    fontFamily: {
      sans: ["Noto Sans", "sans-serif"],
      rc: ["Noto Sans", "sans-serif"],
    },
    fontSize: {
      "heading-xl-dt": ["40px", "48px"],
      "heading-xl": ["28px", "36px"],
      "heading-l-dt": ["30px", "36px"],
      "heading-l": ["22px", "30px"],
      "heading-m-dt": ["20px", "28px"],
      "heading-m": ["16px", "24px"],
      "heading-s": ["14px", "22px"],
      "caption-xl-dt": ["22px", "28px"],
      "caption-xl": ["16px", "22px"],
      "caption-l-dt": ["20px", "24px"],
      "caption-l": ["15px", "19px"],
      "caption-m-dt": ["16px", "20px"],
      "caption-m": ["14px", "18px"],
      "form-field": ["14px", "18px"],
      "body-l-dt": ["16px", "24px"],
      "body-l": ["14px", "22px"],
      "body-s-dt": ["14px", "20px"],
      "body-s": ["12px", "16px"],
      legend: ["16px", "20px"],
      link: ["14px", "22px"],
      "text-btn": ["14px", "20px"],
    },
    fontWeight: {
      regular: 400,
      medium: 500,
      bold: 700,
    },
    padding: {
      sm: "8px",
      md: "16px",
      lg: "24px",
      xl: "36px",
      xxl: "48px"
    },
    margin: {
      xs: "4px",
      sm: "8px",
      md: "16px",
      lg: "24px",
      xl: "64px",
    },
    borderWidth: {
      default: "1px",
      0: "0",
      2: "1px",
      4: "4px",
      10: "10px",
    },
    boxShadow: {
      card: "0px 0px 5px 0px #22222270",
      radiobtn: "0 0 0 5px #a82227",
    },
    inset: {
      0: 0,
      10: "10px",
    },
    extend: {},
  },
  variants: {},
  plugins: [],
};
