import { PGRIcon } from "@mseva/digit-ui-react-components";

export const quickServiceModules = {
  modules: [
    {
      moduleCode: "PGR",
      moduleName: "Grivance",
      bgColor: "#ffab2d",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/pgr/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "Swach",
      moduleName: "Grivance",
      bgColor: "#ffab2d",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/swach/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "PT",
      moduleName: "Grivance",
      bgColor: "#4B49AC",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/pt/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "OBPS",
      moduleName: "Grivance",
      bgColor: "#00cccd",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/obps/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "TL",
      moduleName: "Grivance",
      bgColor: "#3e4b5b",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/tl/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "Payment",
      moduleName: "Grivance",
      bgColor: "#0a3622",
      labelKey: "",
      icon: "",
      routes: "",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "HRMS",
      moduleName: "Grivance",
      bgColor: "#4B49AC",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/hrms/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "SW",
      moduleName: "Grivance",
      bgColor: "#00cccd",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/ws/sewerage/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "WS",
      moduleName: "Grivance",
      bgColor: "#ffab2d",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/ws/water/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "MCollect",
      moduleName: "Grivance",
      bgColor: "#3e4b5b  ",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/mcollect/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "Engagement",
      moduleName: "Grivance",
      bgColor: "#0a3622",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/engagement/surveys/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "PTR",
      moduleName: "Grivance",
      bgColor: "#00cccd",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/engagement/surveys/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
    {
      moduleCode: "NDC",
      moduleName: "No Due Certificate",
      bgColor: "#4B49AC",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/ndc/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
    },
  ],
};
