import { PGRIcon } from "@mseva/digit-ui-react-components";

export const quickServiceModules = {
  modules: [
    {
      moduleCode: "PGR",
      moduleName: "Grivance",
      bgColor: "#ffab2d",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/pgr/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "Swach",
      moduleName: "Swach",
      bgColor: "#00cccd",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/swach/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "PT",
      moduleName: "Property Tax",
      bgColor: "#4B49AC",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/pt/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "OBPS",
      moduleName: "Online Building Plan",
      bgColor: "#00cccd",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/obps/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "BPAStakeholder",
      moduleName: "Professional Registration",
      bgColor: "#00cccd",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/obps/stakeholder-inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "Layout",
      moduleName: "Layout",
      bgColor: "#00cccd",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/obps/layout/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "TL",
      moduleName: "Trade License",
      bgColor: "#3e4b5b",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/tl/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "Payment",
      moduleName: "Payment",
      bgColor: "#0a3622",
      labelKey: "",
      icon: "",
      routes: "",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "HRMS",
      moduleName: "HRMS",
      bgColor: "#4B49AC",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/hrms/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "SW",
      moduleName: "Sewerage Tax",
      bgColor: "#00cccd",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/ws/sewerage/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "WS",
      moduleName: "Water Tax",
      bgColor: "#ffab2d",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/ws/water/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "MCollect",
      moduleName: "MCollect",
      bgColor: "#3e4b5b  ",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/mcollect/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "ChallanGeneration",
      moduleName: "Challan Generation",
      bgColor: "#3e4b5b  ",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/challangeneration/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "RentAndLease",
      moduleName: "Rent And Lease",
      bgColor: "#3e4b5b  ",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/rentandlease/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "Engagement",
      moduleName: "Social Survey",
      bgColor: "#0a3622",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/engagement/surveys/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "PTR",
      moduleName: "Pet Registration",
      bgColor: "#00cccd",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/ptr/petservice/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "NDC",
      moduleName: "No Due Certificate",
      bgColor: "#4B49AC",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/ndc/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "SV",
      moduleName: "Street Vending",
      bgColor: "#3e4b5b  ",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/sv/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "ADS",
      moduleName: "Advertisement",
      bgColor: "#3e4b5b  ",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/ads/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "CHB",
      moduleName: "Venue Booking",
      bgColor: "#3e4b5b",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/chb/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "ASSET",
      moduleName: "Asset",
      bgColor: "#3e4b5b",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/asset/assetservice/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "NOC",
      moduleName: "No Objection Certificate",
      bgColor: "#3e4b5b",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/noc/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "CLU",
      moduleName: "Change of Land Use",
      bgColor: "#3e4b5b",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/obps/clu/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
    {
      moduleCode: "GarbageCollection",
      moduleName: "Garbage Collection",
      bgColor: "#3e4b5b",
      labelKey: "",
      icon: "",
      routes: "/digit-ui/employee/garbagecollection/inbox",
      isCitizen: false,
      description: "",
      subHeading: "",
      roles: [],
    },
  ],
};
